//css
import './css/font.css'
import './css/reset.css'
import './css/root.css'
import './css/common.css'
import './css/login.css'
import './css/session.css'
import './css/main.css'
import './css/main_header.css'
import './css/notify.css'
import './css/dropmenu.css'
import './css/login_dropmenu.css'
import './css/admin_portal.css'
import './css/sensor_type.css'
import './css/popup.css'
import './css/main_container.css'
import './css/detail.css'
import './css/containers/device.css'
import './css/containers/net.css'
import './css/containers/detail.css'
import './css/containers/image_app_details.css'
import './css/containers/device_details.css'
import './css/containers/device_description.css'
import './css/containers/tree_graph.css'
import './css/containers/image.css'
import './css/containers/app.css'
import './css/containers/jobs.css'
import './css/containers/sensor_graph.css'
import './css/containers/sensor_description.css'
import './css/containers/notification.css'
import './css/containers/device_notification.css'
import './css/commands/common.css'
import './css/commands/ac_load.css'
import './css/commands/packets.css'
import './css/commands/time.css'
import './css/commands/ota.css'
import './css/commands/app.css'
import './css/commands/job.css'
import './css/commands/system.css'
import './css/commands/custom.css'
import './css/commands/custom_response.css'
import './css/report.css'
import './css/effect.css'
import './css/file_input.css'
import './css/graph/line_chart.css'
import '@fortawesome/fontawesome-free/js/fontawesome'
import '@fortawesome/fontawesome-free/js/solid'
// import '@fortawesome/fontawesome-free/js/regular'
import '@fortawesome/fontawesome-free/js/brands'

//components
import "./js/components/x-input-icon.js"
import "./js/components/x-input-server.js"
import "./js/components/overtext-input.js"
import "./js/components/check-switch.js"
import "./js/components/load-screen.js"
import "./js/components/drop-menu.js"
import "./js/components/pop-modal.js"
import "./js/components/detail-line.js"
import "./js/components/expand-menu.js"
import "./js/components/detail-command.js"
import "./js/components/btn-on-off.js"
import "./js/components/array-command.js"
import "./js/components/binary-data.js"
import "./js/components/header-value.js"
import "./js/components/sensor-notify.js"

//js
import './js/pages/login.js'
import './js/pages/main.js'
import './js/main.js'
